name: Generate Snake Animation

on:
  workflow_dispatch:       # allows manual trigger
  schedule:
    - cron: "0 0 * * *"    # runs daily at midnight (UTC)

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: i-am-subrata
          outputs: |
            ./output/snake.svg

      - name: Push to GitHub (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
