name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: i-am-subrata-Subrata
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg?palette=github-dark

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake contribution graph"
          add: "output/*"
